apiVersion: v1
kind: Service
metadata:
  name: {{include "btcpayserver.fullname" .}}
  labels: {{- include "btcpayserver.labels" . | nindent 4}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: {{.Values.service.port}}
      protocol: TCP
      name: http
  selector: {{- include "btcpayserver.selectorLabels" . | nindent 4}}
