apiVersion: v1
kind: Service
metadata:
  name: {{include "specter-desktop.fullname" .}}
  labels: {{- include "specter-desktop.labels" . | nindent 4}}
spec:
  type: {{.Values.service.type}}
  ports:
    - port: {{.Values.service.port}}
      targetPort: specter
      protocol: TCP
      name: specter
  selector: {{- include "specter-desktop.selectorLabels" . | nindent 4}}
